language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
services:
  # we need docker for building the image and mongo for testing
  - docker
  - mongodb
install:
  - yarn install --frozen-lockfile --non-interactive --ignore-engines

jobs:
  include:
    - stage: Build and Test
      script:
      - yarn add codacy-coverage
      - yarn eslint
      - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha -- test/ --timeout=10000 --exit
      - cat ./coverage/lcov.info | codacy-coverage
      - docker build -t humanconnection/embed-api:latest .

after_success:
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push humanconnection/embed-api:latest;
    fi
