language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
services:
  # we need docker for building the image and mongo for testing
  - docker
  - mongodb
install:
  - yarn install --production=false --frozen-lockfile --non-interactive --ignore-engines

jobs:
  include:
    - stage: Build and Test
      script:
      - yarn add codacy-coverage
      - yarn eslint
      - cross-env NODE_ENV=test ./node_modules/.bin/nyc --reporter=lcov --reporter=text ./node_modules/.bin/mocha test/*.js --timeout=10000
      - cat ./coverage/lcov.info | codacy-coverage
      - docker build -t humanconnection/embed-api:latest .

after_success:
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push humanconnection/embed-api:latest;
    fi
